theme = "horizon-dark"

[editor]
line-number = "relative"
true-color = true
cursorline = true
lsp.display-inlay-hints = true
scrolloff = 10
bufferline = "multiple"


[editor.cursor-shape]
insert = "bar"

[keys.normal]
# Quick iteration on config changes
# C-S-o = ":config-open"
# C-r = ":config-reload"
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]
"A-k" = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]
esc = ["collapse_selection", "keep_primary_selection"]

# S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable
[keys.select]
"A-k" = ["goto_line_end","extend_line_below",  "delete_selection", "move_line_up", "paste_before", "select_mode"]
"A-j" = ["goto_line_end","extend_line_below",  "delete_selection", "paste_after", "select_mode" ]

[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]
j = {j = "normal_mode"}
